# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2812f592bdb7776efa2e1128f3d6ec06d7300c2a002ead8575ef222f79e6f83b5e512a6b39ca93d03f1d24c6144494da99e09f6a662f189716e37e135171a66

test:
  secret_key_base: 33e2fb8cd821f3517d413d9572a2f98518a57cd2c36ad00fd5b02810284ff2f7cf1dd81d9655e3d4337bf661a00e609d54df93e7d06fa6794850d04708794741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
