# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9996676e9f95e55f141f36476bec495c079e2d4f1c3c56e498daf735770a67914d55b8ab4036b1b8f23e486d8b56a9c7d757a9b497489c10e33b4889130c16c

test:
  secret_key_base: 8d1be777f46f9cbdde835ea40c4905a9342de3840668966ac637da564cfe229add6938dc3b1ff6c9c63f088bae745e3123dbae8b4eae3ee13d8ee600d106721b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
