# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 489997b92a131b128a81aa56a522ae4267eaa7384e4931065e92eae00a149cc85deb5bde42c5f956831ad2aac367b2c74891f01a5f7b61a16dc890d7853bafee

test:
  secret_key_base: 9ee54da959dc44e18bc7d72794fdb8c6bc68997d0136b9f935d35e01808d5dfde8d957848254fa7f241078972104ea29e42ab87913f7415b61e242a69f7c6665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
