# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb3f3c9b818d163cf1ef0e66ae2f3cd2758e304937b6c115d3a9d684e94d239ff4bd82201722c9f6d5354a045edddbd7656d0757630ac6b6a8a343e96a2d1355

test:
  secret_key_base: 79fce8d4f17c717b1a282f74e5ca0d50145d51b88cc7089208c4604efefffabbbc357b043c622342331af8017df0d5c518179f8fa932b9a871e3743732fb7607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
